### ISSUE TITLE
კონტრიბუციის წესების საჭიროება

### ISSUE THREAD

**Issue by getsadzeg** [lapptech/100Startups#18]
რეპოზიტორიაში გვაქვს contributing.md ფაილი, რომელიც წესით უნდა ემსახურებოდეს კონტრიბუციის წესების გაცნობას საზოგადოებისთვის, მაგრამ გამოყენებული Framework-ის default-ია მგონი. ჯობია თავიდან დაიწეროს,ქართულად.

**Comment by ShavidzeT** [comment]
:+1: გეთანხმები
@Tornikegn გვესაჭიროება მართლაც

**Comment by getsadzeg** [comment]
შემიძლია ჩემს თავზე ავიღო.

**Comment by ShavidzeT** [comment]
@getsadzeg მიხედე გური :heart_eyes:
