### ISSUE TITLE
გრამატიკული და სხვა საკითხები

### ISSUE THREAD

**Issue by Tornikegn** [lapptech/100Startups#2]
~~1. კითხვით წინადადებებზე კითხვის ნიშნები.~~

~~2. მე-6 სტეპპზე "რამელიას" ნაცვლად "რომელია".~~

~~3. სვაიპი მაუსზე გასათიშია.~~

~~4. ტელეფონზე - ინფუთის ფოკუსი დარჩეს მაგრამ გაითიშოს კლავიატურა.~~

~~5. ფოტოს ატვირთვა optional ხომ არ იყოს?~~

**Comment by Tornikegn** [comment]
@vardidzel ლაშა აქ რაც მოგვარებულია დააქლოუზე და დანარჩენები @ShavidzeT -სთან ერთად გაიარე და გადაჭერი.

**Comment by ShavidzeT** [comment]
1. & 2. მოგვარებულია და მივყვები

**Comment by ShavidzeT** [comment]
მაუსის სვაიპზე გასათიშად ბევრი არ მიწვალია და სოლუშენის სხვა ხერხს მივმართე, ვაფიქსირებ დევაისი მობილურია(ამ შემთხვევაში მობილურში იგულისხმება თაჩსქრინიანი დევაისები) თუ არა, ხოლო სვაიპი შეუძლია მხოლოდ მობილურს.

მაგრამ ეს მთლად ასეც არაა, შეიძლება თაჩი ჰქონდეს მაგრამ დესკტოპი იყოს.

მოკლედ კოდი აქაა, რაღაც ეტაპზე დავააფდეითებ ალბათ სვაიპის ფუნქციონალს, რადგან jquery ui-ს მგონი მარტო მაგისთვის ვაიმპორტებ.

კოდიც აქაა: https://gist.github.com/ShavidzeT/67bd0892f3973f49020c6cf5dc98643c

**Comment by ShavidzeT** [comment]
ფოტოს ატვირთვა გახდა optional, მაგრამ გაითვალისწინეთ რომ ამ პატჩებმა შეიძლება უარყოფითი გავლენა მოახდინოს სხვა სერვისებზე, ამიტომ დეტალურად უნდა გავტესტოთ კიდევ.
