### ISSUE TITLE
0.9.7 არასრული ვერსია გამოშვებულია

### ISSUE THREAD

**Issue by ShavidzeT** [lapptech/100Startups#26]
@lapptech/andromeda 
ახალი ვერსია უკვე გამოშვებულია!
ანდრომედას გუნდის წევრებს და მთლიანად ამ პროექტის დახმარების მსურველებს ვთხოვ რომ გატესტოთ მიმდინარე ვებ-გვერდი, ნებისმიერი დეტალი, არ აქვს მნიშვნელობა იქნება ეს პროგრამული შეცდომა თუ UI/UX.
გატესტეთ და თქვენი პასუხი გთხოვთ, რომ დააფიქსიროთ ნათლად, ბაგების არ პოვნის შემთხვევაშიც...

**Comment by getsadzeg** [comment]
შეიძლება სატესტო მონაცემები შევიყვანო? ოღონდ მონაცემთა ბაზას არ გადავავსებ :laughing:

**Comment by ShavidzeT** [comment]
რათქმაუნდა, იმდენჯერ შეგიძლია შეიყვანო რამდენჯერაც გინდა, თუ გინდა dos attack გაუშვი, ან სერვერი დაჰაკე თუ შეძლებ :P

**Comment by getsadzeg** [comment]
:D Ddos კარგი იდეაა :smiling_imp: :laughing:
