### ISSUE TITLE
დაფიქსირებული შეცდომის ჩვენების ოპტიმიზაცია

### ISSUE THREAD

**Issue by getsadzeg** [lapptech/100Startups#27]
სასურველი იქნება თუ ინფორმაციის არასწორ ფორმატში და ა.შ. შეყვანისას მაშინვე დაიწერება,რომ ესა და ეს ინფორმაცია ამა და ამ მიზეზის გამო არასწორადაა შეყვანილი.

მაგალითად, მე-8 ეტაპზე მეილის ასეთნაირად შეყვანისას:

![selection_244](https://cloud.githubusercontent.com/assets/9250896/15228490/7ac8565a-189d-11e6-8457-5326ea7184ff.png)

Error-ი იწერება მხოლოდ ბოლო ეტაპზე:

![selection_245](https://cloud.githubusercontent.com/assets/9250896/15228525/9f685c6c-189d-11e6-9cc7-16a03696ba11.png)

რა აზრის ხართ? იქნებ ჯობდეს რომ მაშინვე დაეწეროს,რომ დაფიქსირებულია შეცდომა?

**Comment by ShavidzeT** [comment]
გური კარგი კითხვაა, უბრალოდ პროექტი თავიდანვე ისეა გათვლილი, რომ შეცდომები შეგნებულად ბოლო სტეპზე ამოგიგდოს, მაგას რომ თავი დავანებოთ ინფუთუთებში მოთხოვნილი ქონთენთი ძალიან მარტივი იდეის მატარებელია და თუ ვინმე არასეორად შეიყვანს მას ბოლო სტეპზე იხილავს შეცდომებს, შესაბამისად ვერ დარეგისტრირდება, მაგრამ ის მომხმარებელიც გავითვალისწინეთ ვისაც არ უნდა რომ შეავსოს პირველი სტეპი ან სხვა რომელიმე და სურს ნახოს სხვა სტეპების მოთხოვნები. ყოველ ეტაპზე შემოწმება ვიფიქრეთ, რომ უბრალოდ uiს მხარეს გააფუჭბდა, მაგრამ მემგონი ამ მიდგომით uxსაც არ ვუფუჭბთ

**Comment by getsadzeg** [comment]
გასაგებია, ვხურავ.
