### ISSUE TITLE
SMS Office API Key

### ISSUE THREAD

**Issue by ShavidzeT** [lapptech/100startups#37]
უნდა შევცვალოთ API key, რადგან კოდში შემთხვევით გამეპარა უნიკალური გასაღები, რისი მიხედვითაც იგზავნება მეილები, ის აფიქსირებს იდენტობას, შესაბამისად ამ გასაღების საშუალებით შეძლებენ სხვებიც მესიჯის გაგზავნას 100startups-ის სახელით, მაგრამ "ვერ მოგართვით".
დღეს შევცვლით @Tornikegn :smile:

**Comment by getsadzeg** [comment]
აჰა :joy: ეგეთი ინფორმაცია არ უნდა იპარებოდეს, ხო ვამბობდი მეც ადრე

**Comment by ShavidzeT** [comment]
@getsadzeg API Key შევცვალეთ და ინტეგრაციაც მოვახდინეთ საიტზე და ის რა გასაღებიც ჩანს ჰისტორიში ეგ უკვე არააქტიურია, ასე, რომ მსგავსი სახის შეცდომები აღარ განმეორდება.
მადლობა ამ რეპოს https://github.com/vlucas/phpdotenv
