### ISSUE TITLE
keypress

### ISSUE THREAD

**Issue by Tornikegn** [lapptech/100Startups#6]
<strike>1- მე-8 სტეპზე პრაბელი გასათიშია</strike>
~~2- მე-3 სტეპზე სახელის და გვარის ინფუთში რიცხვები გასათიშია~~

**Comment by Tornikegn** [comment]
@vardidzel დღეს სცადე კიდევ ამ პრობლემის მოგვარება.

**Comment by ShavidzeT** [comment]
სახელსა და გვარში მხოლოდ ალფაბეტის შეყვანაა შესაძლებელი...
@Tornikegn ნახე და როცა მოახერხებ გატესტვას issue დახურე. :boom:
