### ISSUE TITLE
icon-ის საჭიროება

### ISSUE THREAD

**Issue by getsadzeg** [lapptech/100Startups#8]
პატარა წვრილმანი: ს**აიტს აკლია icon.** :laughing:

**Comment by Tornikegn** [comment]
@ShavidzeT ისევ ძველ აიკონს მიჩვენებს დღეს საიტზე შესვლისას და დროებით იყოს.

**Comment by getsadzeg** [comment]
ნამდვილად იგივეს აჩვენებს, არადა განახლებული უნდა იყოს თითქოს.

[https://github.com/lapptech/100Startups/commit/35e9158c9bf0b30fc3954df21e0273c85a85ca04](url)

აი,ნამდვილად განახლებულია.

**Comment by ShavidzeT** [comment]
ვმუშაობთ ახლა მე და ანი icon-ზე და please wait :100:

**Comment by ShavidzeT** [comment]
favicon განვაახლეთ და რამოდენიმე ვარიანტი შევიმუშავეთ, რომელიც ყველაზე ძალიან მოგვეწონა ახლახანს გავუშვით და ასევე შეგიძლიათ ნახოთ სხვა ვარიანტებიც, ოღონდ მალე ნახეთ ამ ლინკზე, რომ უნდა ჩავკეტო ეს Directory :smile: http://100startups.ge/assets/img/

**Comment by getsadzeg** [comment]
მრგვალი ვარიანტი მომეწონა მე პირადად, კონკრეტულად **favicon2**

**Comment by getsadzeg** [comment]
მგონი კარგია :+1:

**Comment by ShavidzeT** [comment]
@getsadzeg ცოტახანი ღიად დავტოვოთ, სხვების პასუხებიც მოვისმინოთ :palm_tree:
